services:
  documind-ai:
    image: documind-ai
    container_name: documind-container

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./uploads:/app/uploads
      - ./vectorstore:/app/vectorstore

    restart: unless-stopped